# Definicja wszystkich obiekrów w środowisku

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for Astro project deployment with S3 and CloudFront (No custom domain)

Parameters:
  ProjectName:
    Type: String
    Default: dev
    Description: The environment to deploy to (e.g., dev, prod)


Resources:
  BackendRepository: 
    Type: AWS::ECR::Repository


  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: FargateSzkolenieCluster
      CapacityProviders:
        - FARGATE
      DefaultCapacityProviderStrategy:
        - CapacityProvider: FARGATE
          Weight: 1
      Configuration:
        ExecuteCommandConfiguration:
          Logging: DEFAULT


  BackendTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      RequiresCompatibilities:
          - FARGATE
      NetworkMode: awsvpc
      ContainerDefinitions:
        - Name: AppName
          Image: !GetAtt BackendRepository.RepositoryUri
          Cpu: 256
          PortMappings:
            - ContainerPort: 8080
              HostPort: 8080
              Protocol: tcp
          Memory: 512
          Essential: true
  

  BackendECSService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: cfn-service
      Cluster: !Ref ECSCluster
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - sg-034be41c41305fa7c
          Subnets:
            - subnet-01fca484b79d487c1
            - subnet-0e2c93a24cb1a9963
      TaskDefinition: !Ref BackendTaskDefinition


Outputs:
  BackendRepositoryUri:
    Description: URI of the ECR repository
    Value: !GetAtt BackendRepository.RepositoryUri
    Export:
      Name: !Sub "${ProjectName}-BackendRepositoryUri"
  
  BackendRepositoryName:
    Description: Name of the ECR repository
    Value: !Ref BackendRepository
    Export:
      Name: !Sub "${ProjectName}-BackendRepositoryName"


# dodać cluster, task definition etc